# Generated by Django 5.1.6 on 2025-02-18 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(db_index=True, max_length=255)),
                ('iso3_code', models.CharField(blank=True, max_length=3, null=True)),
                ('iso2_code', models.CharField(blank=True, max_length=2, null=True)),
                ('loc_type_id', models.IntegerField(blank=True, null=True)),
                ('loc_type_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var_id', models.IntegerField()),
                ('variant', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LifeExpectancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_year', models.IntegerField()),
                ('life_expectancy_both', models.FloatField()),
                ('life_expectancy_male', models.FloatField()),
                ('life_expectancy_female', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='life_expectancies', to='api.location')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='life_expectancies', to='api.variant')),
            ],
            options={
                'indexes': [models.Index(fields=['location'], name='api_lifeexp_locatio_e61e3f_idx'), models.Index(fields=['variant'], name='api_lifeexp_variant_3bd093_idx')],
            },
        ),
    ]
